from dataclasses import dataclass
from ochra_common.base import DataModel
import uuid
from enum import Enum
from datetime import datetime
from .operation_result import OperationResult


@dataclass
class Operation(DataModel):
    """
    Abstract operation class to be generated by the system
    whenever an agent/device performs an action.

    Attributes:
        _caller (uuid.UUID): The unique identifier of the caller.
        _method (str): The method name that was called.
        _args (dict): A dictionary of arguments passed to the method.
        status (Enum): The current status of the operation.
        start_timestamp (datetime): The timestamp when the operation started.
        end_timestamp (datetime): The timestamp when the operation ended.
        result (list[OperationResult]): A list of results from the operation.
    """
    _caller: uuid.UUID
    _method: str
    _args: dict
    status: Enum
    start_timestamp: datetime
    end_timestamp: datetime
    result: list[OperationResult]
