from pydantic import Field
import uuid
from datetime import datetime
from typing import Dict, Any
from ..base import DataModel
from ..utils.enum import OperationStatus
from .operation_result import OperationResult


class Operation(DataModel):
    """
    Abstract operation class to be generated by the system
    whenever an agent/device performs an action.

    Attributes:
        caller_id (uuid.UUID): The unique identifier of the caller.
        method (str): The method name that was called.
        args (Dict[str, Any]): A dictionary of arguments passed to the method.
        status (Enum): The current status of the operation. Defaulted to CREATED
        start_timestamp (datetime): The timestamp when the operation started.
        end_timestamp (datetime): The timestamp when the operation ended.
        result (List[OperationResult]): A list of results from the operation.
    """

    caller_id: uuid.UUID
    method: str
    args: Dict[str, Any]
    status: OperationStatus = OperationStatus.CREATED
    start_timestamp: datetime = Field(default=None)
    end_timestamp: datetime = Field(default=None)
    result: OperationResult = Field(default=None)

    _endpoint = "operations"  # associated endpoint for all operations

    def add_result(self, result: OperationResult):
        """
        Add a result to the operation.

        Args:
            result (OperationResult): The result of the operation.
        """
        raise NotImplementedError
