from abc import abstractmethod
from dataclasses import dataclass, field
from ochra_common.base import DataModel
import uuid
from enum import Enum
from datetime import datetime
from typing import List, Dict, Any
from .operation_result import OperationResult

_COllECTION = "operations"


@dataclass(kw_only=True)
class Operation(DataModel):
    """
    Abstract operation class to be generated by the system
    whenever an agent/device performs an action.

    Attributes:
        caller_id (uuid.UUID): The unique identifier of the caller.
        method (str): The method name that was called.
        args (Dict[str, Any]): A dictionary of arguments passed to the method.
        status (Enum): The current status of the operation.
        start_timestamp (datetime): The timestamp when the operation started.
        end_timestamp (datetime): The timestamp when the operation ended.
        result (List[OperationResult]): A list of results from the operation.
    """
    caller_id: uuid.UUID
    method: str
    args: Dict[str, Any]
    status: Enum = -1  # TODO: Define OperationStatus Enum
    start_timestamp: datetime = field(init=False, default=None)
    end_timestamp: datetime = field(init=False, default=None)
    result: List[OperationResult] = field(init=False, default_factory=list)

    def __post_init__(self):
        self._collection = _COllECTION
        return super().__post_init__()

    def add_start_timestamp(self, timestamp: datetime):
        """
        Add a start timestamp to the operation.

        Args:
            timestamp (datetime): The timestamp when the operation started.
        """
        self.start_timestamp = timestamp

    def add_end_timestamp(self, timestamp: datetime):
        """
        Add an end timestamp to the operation.

        Args:
            timestamp (datetime): The timestamp when the operation ended.
        """
        self.end_timestamp = timestamp

    @abstractmethod
    def add_result(self, result: OperationResult):
        """
        Add a result to the operation.

        Args:
            result (OperationResult): The result of the operation.
        """
        pass
